version: "3"
services:
  amplify:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cache
      - aws-data:/root/.aws
      - amplify-data:/root/.amplify
    env_file:
      - .env
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
      DYNAMO_ENDPOINT_URL: http://dynamodb-local:8000
      ENVIRONMENT: local

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./data:/data"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000

volumes:
  aws-data:
  amplify-data:
